version: '3.7'

services:
  app:
    build: .
    env_file:
      - auth.env 
    volumes:
      - .:/usr/src/themoviepredictor
    networks: 
      - database_net
    command: tail -f /dev/null
    depends_on: 
      - database
  database:
    image: mysql:latest
    environment:
      - auth.env
    networks:
      - database_net
    # ports:
    #   - 3306:3306
    # plus besoin de publier le port puisqu'on n'éxécute plus le script python sur notre machine en local mais dans le container
    volumes:
      - database_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    command: --default_authentication_plugin=mysql_native_password
  adminer:
    image: dehy/adminer
    networks:
      - database_net
    ports:
      - 8080:80

networks:
  database_net:
    driver: bridge

volumes:
  database_data: